import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatUserName } from "./user-display";
import type { getSheetWithDetail } from "./hours-on-site";

// Maps the Prisma getSheetWithDetail() shape into generateHoursOnSitePdf's
// params — the one place that translation happens, reused by both the
// download route and the email route so they can never drift apart.
export function paramsFromSheet(sheet: NonNullable<Awaited<ReturnType<typeof getSheetWithDetail>>>) {
  return {
    projectName: sheet.project.name,
    variationItemReference: sheet.variationItem?.reference ?? null,
    variationItemTitle: sheet.variationItem?.title ?? null,
    comments: sheet.comments,
    startedAt: sheet.startedAt,
    finishedAt: sheet.finishedAt,
    totalHours: sheet.totalHours != null ? Number(sheet.totalHours) : null,
    workerNames: sheet.workers.map((w) => w.worker.name),
    createdByName: formatUserName(sheet.createdByUser) ?? sheet.createdByUser.email
  };
}

// Generated fresh every time it's needed (viewed or emailed) from the
// sheet's CURRENT data — deliberately not a stored/frozen file, since
// hours/workers/comments must stay editable indefinitely (see
// HoursOnSiteSheet's schema comment). A stored file would either go stale
// after an edit or need regenerating anyway, so there's no "frozen
// snapshot" here the way VariationPackage deliberately is one.
export async function generateHoursOnSitePdf(params: {
  projectName: string;
  variationItemReference: string | null;
  variationItemTitle: string | null;
  comments: string | null;
  startedAt: Date;
  finishedAt: Date | null;
  totalHours: number | null;
  workerNames: string[];
  createdByName: string;
}) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = 780;
  const left = 50;
  const lineHeight = 20;

  function drawLabelValue(label: string, value: string) {
    page.drawText(label, { x: left, y, size: 11, font: boldFont, color: rgb(0.08, 0.08, 0.1) });
    page.drawText(value, { x: left + 150, y, size: 11, font, maxWidth: 395 });
    y -= lineHeight;
  }

  page.drawText("Hours on Site", { x: left, y, size: 22, font: boldFont, color: rgb(0.08, 0.08, 0.1) });
  y -= 36;

  drawLabelValue("Project:", params.projectName);
  if (params.variationItemReference) {
    drawLabelValue("Site Instruction:", `${params.variationItemReference} — ${params.variationItemTitle ?? ""}`);
  } else if (params.comments) {
    drawLabelValue("Comments:", params.comments);
  }
  drawLabelValue("Start time:", params.startedAt.toLocaleString("en-NZ"));
  drawLabelValue("Finish time:", params.finishedAt ? params.finishedAt.toLocaleString("en-NZ") : "Not yet finished");
  drawLabelValue("Total hours:", params.totalHours != null ? `${params.totalHours.toFixed(2)} hrs` : "—");
  drawLabelValue("Recorded by:", params.createdByName);

  y -= 10;
  page.drawText("Workers on site", { x: left, y, size: 13, font: boldFont, color: rgb(0.08, 0.08, 0.1) });
  y -= lineHeight;

  if (params.workerNames.length === 0) {
    page.drawText("(none recorded)", { x: left, y, size: 11, font, color: rgb(0.3, 0.3, 0.35) });
    y -= lineHeight;
  } else {
    for (const name of params.workerNames) {
      page.drawText(`•  ${name}`, { x: left, y, size: 11, font });
      y -= lineHeight;
    }
  }

  y -= 20;
  page.drawText("Generated by Subbie HQ — supporting evidence for a variation claim.", {
    x: left,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.45)
  });

  const pdfBytes = await pdfDoc.save();
  return new Uint8Array(pdfBytes);
}
