// Mandatory on every AI-drafted response letter — shown on-screen wherever a
// draft is displayed/edited AND appended verbatim to the letter text itself
// (by code, not left to the model — see draftResponseLetter in lib/grok.ts),
// so it can never be silently dropped when the letter is copied, exported,
// or sent. Per the founder's brief, adjust tone but keep this substance.
export const RESPONSE_LETTER_DISCLAIMER =
  "This document has been generated by automated contract analysis and is provided for guidance only. It does not constitute legal advice. Please have any proposed changes reviewed by a qualified, registered lawyer before relying on or acting upon them.";
